version: '3.9'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/
    links:
      - wordpress
    depends_on:
      - wordpress
    restart: always
    networks:
      - connection

  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    env_file:
      - .env
    environment:
      - WORDPRESS_DB_HOST=${MYSQL_HOSTNAME}
      - WORDPRESS_DB_USER=${MYSQL_USER}
      - WORDPRESS_DB_PASSWORD=${MYSQL_PASSWORD}
      - WORDPRESS_DB_NAME=${MYSQL_DATABASE_NAME}
    links:
      - mariadb
    depends_on:
      - mariadb
    restart: always
    networks:
      - connection

  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    env_file:
      - .env
    environment:
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
      - MYSQL_DATABASE=${MYSQL_DATABASE_NAME}
      - MYSQL_USER=${MYSQL_USER}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD}
    expose:
      - 3306
    restart: always
    networks:
      - connection
volumes:
  wordpress_data:
      name: wordpress
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${LOCAL_DEVICE_WORDPRESS}
  mariadb_data:
      name: mariadb
      driver: local
      driver_opts:
        type: none
        o: bind
        device: ${LOCAL_DEVICE_MARIADB}
networks:
  connection:
    name: connection
    driver: bridge