version: '3.9'
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx
    ports:
      - "443:443"
    volumes:
      - wordpress_data:/var/www/html/wordpress
    links:
      - wordpress
    depends_on:
      - wordpress
    restart: always
    networks:
      - connection
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/html/wordpress
    environment:
      - WORDPRESS_DB_HOST=mariadb
      - WORDPRESS_DB_USER=exampleuser
      - WORDPRESS_DB_PASSWORD=examplepass
      - WORDPRESS_DB_NAME=exampledb
    links:
      - mariadb
    restart: always
    networks:
      - connection
  mariadb:
    container_name: mariadb
    build: ./requirements/mariadb
    volumes:
      - mariadb_data:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=rootpassword
      - MYSQL_DATABASE=exampledb
      - MYSQL_USER=exampleuser
      - MYSQL_PASSWORD=examplepass
    expose:
      - 3306
    restart: always
    networks:
      - connection
volumes:
  wordpress_data:
      name: wordpress
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/bortakuz/data/wordpress
  mariadb_data:
      name: mariadb
      driver: local
      driver_opts:
        type: none
        o: bind
        device: /home/bortakuz/data/mariadb
networks:
  connection:
    driver: bridge